# Generated by Django 4.2.14 on 2024-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_description_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("D", "Done"), ("C", "Cancelled")],
                default="P",
                max_length=20,
            ),
        ),
    ]
