# Generated by Django 4.2.14 on 2024-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mode_of_consumption",
            field=models.CharField(
                choices=[("D", "Dine-In"), ("T", "Take-Out")],
                default="D",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
