# Generated by Django 4.2.14 on 2024-08-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0002_alter_equipmentsinventory_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentsinventory",
            name="batch",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentsinventory",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="rawmaterialsinventory",
            name="batch",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="rawmaterialsinventory",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
