# Generated by Django 4.2.14 on 2024-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0004_inventory_remove_rawmaterialsinventory_branch_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": "inventories"},
        ),
    ]
