# Generated by Django 4.2.14 on 2024-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0005_alter_inventory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Raw Materials", "Raw Materials"),
                            ("Equipments", "Equipments"),
                        ],
                        default="Raw Materials",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="No description provided.",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inventory categories",
            },
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
