# Generated by Django 4.2.14 on 2024-08-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0007_remove_inventorycategory_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "measurement",
                    models.CharField(
                        choices=[("kilograms", "Kilograms"), ("liters", "Liters")],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="in_stock",
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="inventories.inventorycategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
