# Generated by Django 4.2.14 on 2024-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0008_inventoryitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
