# Generated by Django 4.2.14 on 2024-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0009_alter_inventoryitem_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("kilograms", "Kilograms"),
                    ("liters", "Liters"),
                    ("gallons", "Gallons"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
