# Generated by Django 4.2.14 on 2024-08-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_alter_branch_options"),
        ("inventories", "0010_alter_inventoryitem_measurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="storage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
            preserve_default=False,
        ),
    ]
