# Generated by Django 4.2.14 on 2024-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0011_inventoryitem_storage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="storage",
            new_name="branch",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="packaging",
            field=models.CharField(
                choices=[
                    ("Bottle", "Bottle"),
                    ("Gallon", "Gallon"),
                    ("Sack", "Sack"),
                    ("Tray", "Tray"),
                    ("Others", "Others"),
                ],
                default="Bottle",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
