# Generated by Django 4.2.14 on 2024-08-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
