# Generated by Django 4.2.14 on 2024-08-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_alter_branch_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
