# Generated by Django 4.2.14 on 2024-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_alter_branch_created_at_alter_branch_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
