# Generated by Django 4.2.14 on 2024-08-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_alter_branch_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "branches"},
        ),
    ]
